// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Address struct {
	Addressid  int32         `json:"addressid"`
	Userid     sql.NullInt32 `json:"userid"`
	Name       string        `json:"name"`
	Phoneno    string        `json:"phoneno"`
	Houseno    string        `json:"houseno"`
	Area       string        `json:"area"`
	Landmark   string        `json:"landmark"`
	City       string        `json:"city"`
	Pincode    string        `json:"pincode"`
	District   string        `json:"district"`
	State      string        `json:"state"`
	Country    string        `json:"country"`
	Defaultadd sql.NullBool  `json:"defaultadd"`
}

type Admin struct {
	ID             int32        `json:"id"`
	FirstName      string       `json:"first_name"`
	LastName       string       `json:"last_name"`
	Email          string       `json:"email"`
	HashedPassword string       `json:"hashed_password"`
	Phone          int32        `json:"phone"`
	IsAdmin        sql.NullBool `json:"is_admin"`
}

type Brand struct {
	ID        int32  `json:"id"`
	BrandName string `json:"brand_name"`
}

type Cart struct {
	ID         int32         `json:"id"`
	ProductID  sql.NullInt32 `json:"product_id"`
	Quantity   int32         `json:"quantity"`
	Price      int32         `json:"price"`
	TotalPrice int32         `json:"total_price"`
	Userid     sql.NullInt32 `json:"userid"`
}

type Catogery struct {
	ID           int32          `json:"id"`
	CatogeryName sql.NullString `json:"catogery_name"`
}

type Coupon struct {
	ID            int32           `json:"id"`
	CouponCode    sql.NullString  `json:"coupon_code"`
	DiscountPrice sql.NullFloat64 `json:"discount_price"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	Expired       sql.NullTime    `json:"expired"`
}

type Image struct {
	ID        int32         `json:"id"`
	ProductID sql.NullInt32 `json:"product_id"`
	Image     string        `json:"image"`
}

type OderItem struct {
	OrderID     int32          `json:"order_id"`
	UserIDNo    int32          `json:"user_id_no"`
	TotalAmount int32          `json:"total_amount"`
	PaymentID   sql.NullInt32  `json:"payment_id"`
	OrderStatus sql.NullString `json:"order_status"`
	AddID       sql.NullInt32  `json:"add_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type OrderDetail struct {
	Oderid     int32         `json:"oderid"`
	Userid     sql.NullInt32 `json:"userid"`
	Addressid  sql.NullInt32 `json:"addressid"`
	PaymentID  sql.NullInt32 `json:"payment_id"`
	OderItemID sql.NullInt32 `json:"oder_item_id"`
	ProductID  sql.NullInt32 `json:"product_id"`
	Quantity   int32         `json:"quantity"`
	Status     string        `json:"status"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type Payment struct {
	PaymentID     int32         `json:"payment_id"`
	UserID        sql.NullInt32 `json:"user_id"`
	PaymentMethod string        `json:"payment_method"`
	TotalAmount   int32         `json:"total_amount"`
	Status        string        `json:"status"`
	Date          sql.NullTime  `json:"date"`
}

type Product struct {
	ProductID   int32         `json:"product_id"`
	ProductName string        `json:"product_name"`
	Description string        `json:"description"`
	Stock       int32         `json:"stock"`
	Price       int32         `json:"price"`
	CatogeryID  sql.NullInt32 `json:"catogery_id"`
	BrandID     sql.NullInt32 `json:"brand_id"`
}

type Razorpay struct {
	Userid          int32          `json:"userid"`
	Razorpaymentid  string         `json:"razorpaymentid"`
	Razorpayorderid sql.NullString `json:"razorpayorderid"`
	Signature       sql.NullString `json:"signature"`
	Amountpaid      sql.NullString `json:"amountpaid"`
}

type User struct {
	ID             int32          `json:"id"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	Email          string         `json:"email"`
	HashedPassword string         `json:"hashed_password"`
	Phone          int32          `json:"phone"`
	Otp            sql.NullString `json:"otp"`
	IsBlocked      sql.NullBool   `json:"is_blocked"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Wallet struct {
	ID     int32           `json:"id"`
	UserID sql.NullInt32   `json:"user_id"`
	Amount sql.NullFloat64 `json:"amount"`
}

type WalletHistory struct {
	ID             int32           `json:"id"`
	UserID         sql.NullInt32   `json:"user_id"`
	Amount         sql.NullFloat64 `json:"amount"`
	TransctionType sql.NullString  `json:"transction_type"`
	Date           sql.NullTime    `json:"date"`
}

type Wishlist struct {
	ID        int32         `json:"id"`
	Userid    sql.NullInt32 `json:"userid"`
	ProductID sql.NullInt32 `json:"product_id"`
}
