// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAddress(ctx context.Context, addressid int32) error
	DeleteAdmin(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, dollar_1 interface{}) error
	GetAddressByID(ctx context.Context, addressid int32) (Address, error)
	GetAdminByID(ctx context.Context, id int32) (Admin, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListAddresses(ctx context.Context) ([]Address, error)
	ListAdmins(ctx context.Context) ([]Admin, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (Admin, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
